// <auto-generated />
using DespachoWorkspace.Management.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace DespachoWorkspace.Management.Infrastructure.Migrations
{
  [DbContext(typeof(DespachoDbContext))]
    partial class DespachoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DespachoWorkspace.Management.Domain.Entities.TaxObligation", b =>
                {
                    b.Property<Guid>("TaxObligationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("TaxObligationId");

                    b.ToTable("TaxObligations");
                });
#pragma warning restore 612, 618
        }
    }
}
